// <auto-generated />
using System;
using CarShopBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarShopBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318233422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarShopBackend.Models.CartModel", b =>
                {
                    b.Property<Guid>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("CartID");

                    b.ToTable("CartModel");
                });

            modelBuilder.Entity("CarShopBackend.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartID")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WishlistID")
                        .HasColumnType("uuid");

                    b.HasKey("UserID");

                    b.HasIndex("CartID");

                    b.HasIndex("WishlistID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarShopBackend.Models.WishlistModel", b =>
                {
                    b.Property<Guid>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("WishlistID");

                    b.ToTable("WishlistModel");
                });

            modelBuilder.Entity("CarShopBackend.Models.UserModel", b =>
                {
                    b.HasOne("CarShopBackend.Models.CartModel", "Cart")
                        .WithMany()
                        .HasForeignKey("CartID");

                    b.HasOne("CarShopBackend.Models.WishlistModel", "Wishlist")
                        .WithMany()
                        .HasForeignKey("WishlistID");

                    b.Navigation("Cart");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
