// <auto-generated />
using System;
using CarShopBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarShopBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319032606_AddVehicleToListing")]
    partial class AddVehicleToListing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarShopBackend.Models.CartModel", b =>
                {
                    b.Property<Guid>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("CartID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CarShopBackend.Models.ImageModel", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageURI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ListingModelListingID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleModelVehicleID")
                        .HasColumnType("uuid");

                    b.HasKey("ImageID");

                    b.HasIndex("ListingModelListingID");

                    b.HasIndex("VehicleModelVehicleID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingModel", b =>
                {
                    b.Property<Guid>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SaleAmount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VehicleID")
                        .HasColumnType("uuid");

                    b.HasKey("ListingID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingToCartModel", b =>
                {
                    b.Property<Guid>("ListingToCartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingID")
                        .HasColumnType("uuid");

                    b.HasKey("ListingToCartID");

                    b.HasIndex("CartID");

                    b.HasIndex("ListingID");

                    b.ToTable("ListingsToCarts");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingToWishlist", b =>
                {
                    b.Property<Guid>("ListingToWishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WishlistID")
                        .HasColumnType("uuid");

                    b.HasKey("ListingToWishlistID");

                    b.HasIndex("ListingID");

                    b.HasIndex("WishlistID");

                    b.ToTable("ListingToWishlist");
                });

            modelBuilder.Entity("CarShopBackend.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartID")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WishlistID")
                        .HasColumnType("uuid");

                    b.HasKey("UserID");

                    b.HasIndex("CartID");

                    b.HasIndex("WishlistID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarShopBackend.Models.VehicleMakeModel", b =>
                {
                    b.Property<Guid>("VehicleMakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleMakeID");

                    b.ToTable("VehicleMakes");
                });

            modelBuilder.Entity("CarShopBackend.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VehicleMakeID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleTypeID")
                        .HasColumnType("uuid");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleID");

                    b.HasIndex("VehicleMakeID");

                    b.HasIndex("VehicleTypeID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarShopBackend.Models.VehicleTypeModel", b =>
                {
                    b.Property<Guid>("VehicleTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleTypeID");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("CarShopBackend.Models.WishlistModel", b =>
                {
                    b.Property<Guid>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("WishlistID");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("CarShopBackend.Models.ImageModel", b =>
                {
                    b.HasOne("CarShopBackend.Models.ListingModel", null)
                        .WithMany("Images")
                        .HasForeignKey("ListingModelListingID");

                    b.HasOne("CarShopBackend.Models.VehicleModel", null)
                        .WithMany("Images")
                        .HasForeignKey("VehicleModelVehicleID");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingModel", b =>
                {
                    b.HasOne("CarShopBackend.Models.VehicleModel", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingToCartModel", b =>
                {
                    b.HasOne("CarShopBackend.Models.CartModel", "Cart")
                        .WithMany("ListingToCart")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShopBackend.Models.ListingModel", "Listing")
                        .WithMany("ListingToCart")
                        .HasForeignKey("ListingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingToWishlist", b =>
                {
                    b.HasOne("CarShopBackend.Models.ListingModel", "Listing")
                        .WithMany("ListingToWishlist")
                        .HasForeignKey("ListingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShopBackend.Models.WishlistModel", "Wishlist")
                        .WithMany("ListingToWishlist")
                        .HasForeignKey("WishlistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("CarShopBackend.Models.UserModel", b =>
                {
                    b.HasOne("CarShopBackend.Models.CartModel", "Cart")
                        .WithMany()
                        .HasForeignKey("CartID");

                    b.HasOne("CarShopBackend.Models.WishlistModel", "Wishlist")
                        .WithMany()
                        .HasForeignKey("WishlistID");

                    b.Navigation("Cart");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("CarShopBackend.Models.VehicleModel", b =>
                {
                    b.HasOne("CarShopBackend.Models.VehicleMakeModel", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShopBackend.Models.VehicleTypeModel", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("CarShopBackend.Models.CartModel", b =>
                {
                    b.Navigation("ListingToCart");
                });

            modelBuilder.Entity("CarShopBackend.Models.ListingModel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ListingToCart");

                    b.Navigation("ListingToWishlist");
                });

            modelBuilder.Entity("CarShopBackend.Models.VehicleModel", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CarShopBackend.Models.WishlistModel", b =>
                {
                    b.Navigation("ListingToWishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
